export const books: Partial<TRead>[] = [
  {
    title: "Os Analectos",
    authors: "Confúcio",
    cover: "https://i.imgur.com/XGI4tlX.png",
  },
  {
    title: "A política do impossível",
    authors: "Stig Dagerman",
    cover: "https://i.imgur.com/NQ4zjRo.jpeg",
  },
  {
    title: "A cidade dos ricos e a cidade dos pobres",
    authors: "Bernardo Secchi; Renata de Oliveiro Sampaio (trad.)",
    cover: "https://i.imgur.com/gWxSU6P.png",
  },
  {
    title: "Lógica e Dialéctica",
    authors: "Mário Ferreira dos Santos",
    cover: "https://i.imgur.com/h4biNAU.png",
    publisher: "Livraria e Editôra LOGOS Ltda.",
    series: "Enciclopédia de Ciências Filosóficas e Sociais",
  },
  {
    title: "Psicologia",
    authors: "Mário Ferreira dos Santos",
    cover: "https://i.imgur.com/wVS6k5j.png",
    publisher: "Livraria e Editôra LOGOS Ltda.",
    series: "Enciclopédia de Ciências Filosóficas e Sociais",
  },
  {
    title: "Teoria do Conhecimento",
    authors: "Mário Ferreira dos Santos",
    cover: "https://i.imgur.com/tXDQK3R.png",
    publisher: "Livraria e Editôra LOGOS Ltda.",
    series: "Enciclopédia de Ciências Filosóficas e Sociais",
  },
  {
    title: "Ontologia e Cosmologia",
    authors: "Mário Ferreira dos Santos",
    cover: "https://i.imgur.com/ZoWgILN.png",
    publisher: "Livraria e Editôra LOGOS Ltda.",
    series: "Enciclopédia de Ciências Filosóficas e Sociais",
  },
  {
    title: "Tratado de Simbólica",
    authors: "Mário Ferreira dos Santos",
    cover: "https://i.imgur.com/9MDtyOT.png",
    publisher: "Livraria e Editôra LOGOS Ltda.",
    series: "Enciclopédia de Ciências Filosóficas e Sociais",
  },
  {
    title: "Filosofia da Crise",
    authors: "Mário Ferreira dos Santos",
    cover: "https://i.imgur.com/IPrB560.png",
    publisher: "Livraria e Editôra LOGOS Ltda.",
    series: "Enciclopédia de Ciências Filosóficas e Sociais",
  },
  {
    title: "O Homem Perante o Infinito",
    authors: "Mário Ferreira dos Santos",
    cover: "https://i.imgur.com/S3nr6oO.png",
    publisher: "Livraria e Editôra LOGOS Ltda.",
    series: "Enciclopédia de Ciências Filosóficas e Sociais",
  },
  {
    title: "Noologia Geral",
    authors: "Mário Ferreira dos Santos",
    cover: "https://i.imgur.com/tErywJg.png",
    publisher: "Livraria e Editôra LOGOS Ltda.",
    series: "Enciclopédia de Ciências Filosóficas e Sociais",
  },
  {
    title: "Filosofia Concreta, tomo 1.º",
    authors: "Mário Ferreira dos Santos",
    cover: "https://i.imgur.com/uXhgk7Y.png",
    publisher: "Livraria e Editôra LOGOS Ltda.",
    series: "Enciclopédia de Ciências Filosóficas e Sociais",
  },
  {
    title: "Filosofia Concreta, tomo 2.º",
    authors: "Mário Ferreira dos Santos",
    cover: "https://i.imgur.com/YXKVOjb.png",
    publisher: "Livraria e Editôra LOGOS Ltda.",
    series: "Enciclopédia de Ciências Filosóficas e Sociais",
  },
  {
    title: "Filosofia Concreta, tomo 3.º",
    authors: "Mário Ferreira dos Santos",
    cover: "https://i.imgur.com/T8thUn7.png",
    publisher: "Livraria e Editôra LOGOS Ltda.",
    series: "Enciclopédia de Ciências Filosóficas e Sociais",
  },
  {
    title: "Filosofia Concreta dos Valôres",
    authors: "Mário Ferreira dos Santos",
    cover: "https://i.imgur.com/EeQHhnw.png",
    publisher: "Livraria e Editôra LOGOS Ltda.",
    series: "Enciclopédia de Ciências Filosóficas e Sociais",
  },
  {
    title: "Sociologia Fundamental e Ética Fundamental",
    authors: "Mário Ferreira dos Santos",
    cover: "https://i.imgur.com/hnk3UMV.png",
    publisher: "Livraria e Editôra LOGOS Ltda.",
    series: "Enciclopédia de Ciências Filosóficas e Sociais",
  },
  {
    title: "Tao Te Ching: O livro do Tao e da virtude",
    authors: "Lao Tsé",
    cover: "https://i.imgur.com/O55UoIH.png",
  },
];
